jwt:
    secret: 89af50d28b1f4bac967b137068e91c7489af50d28b1f4
spring:
    data:
        mongodb:
            database: tweet-app
            host: localhost
            port: 27017
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

BearerAuth:
    type: http
    scheme: bearer
security:
  - ApiKeyAuth: []
paths:
  /test:
    get:
      security:
        - ApiKeyAuth: []   # Use OAuth with a different scope
      responses:
        '200':
          description: OK
        '401':
          description: Not authenticated
        '403':
          description: Access token does not have the required scope
